### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Saikosenpai** [genesor/OPGG_Spectate_Mac#10]
When I drag the .bat file into the app it does nothing at all, it only changes from "Drop your spectate file here" to "Drop your spectate file".

**Comment by genesor** [comment]
Try to launch my app as "admin" http://www.wikihow.com/Open-Applications-With-Root-Privileges-on-a-Mac instead of textEdit you need to type : sudo "/Applications/OP.GG Spectate 1.0.app/Contents/MacOS/node-webkit"

**Comment by Saikosenpai** [comment]
Doesn't work, said a couple errors on terminal, it opened the app up, I tried to drag the .bat file from finder into the app again but it didn't work.
