### ISSUE TITLE
Immediate Bugsplat on League of Legends Launch

### ISSUE THREAD

**Issue by terbmada** [genesor/OPGG_Spectate_Mac#13]
When I drop the replay file, it opens the League of Legends app but crashes and opens bugsplat reporter straight away

**Comment by hbZwart** [comment]
Got the same problem =/

**Comment by tiagoblackcode** [comment]
The best way for you to diagnose the problem would be to do the system call manually through the Terminal.app so we can see the debug output. If you feel like so, launch /Applications/Terminal.app and, assuming you have League of Legends.app in /Applications you can do the following:

```
lolpath=/Applications/League\ of\ Legends.app
gameclientpath=$( echo $lolpath/Contents/LOL/RADS/solutions/lol_game_client_sln/releases/*/deploy/LeagueOfLegends.app )
airclientbinary=$( echo $lolpath/Contents/LOL/RADS/projects/lol_air_client/releases/*/deploy/bin/LolClient )

cd "$gameclientpath/Contents/MacOS"

riot_launched=true \
"$gameclientpath/Contents/MacOS/LeagueofLegends" \
"8394" "LoLPatcher" \
"$airclientbinary" \
"spectator 110.45.191.11:80 abcdefg 0000 KR"
```

We'll use dummy arguments as you can see above (`abcdefg` and  `0000`) to test the application bootstrap only - RADS, Network, OpenGL, etc. If all goes well the screen will turn black and stay like that (we have dummy arguments, hence the spectator feature can't find anything on the server) and you can close the window by pressing `Cmd+Alt+Esc` twice or so. You can then paste here the console output until it starts looping the following:

```
<unknown>(0xa06991a8): ALWAYS| Sleeping
<unknown>(0xa06991a8): ALWAYS| Start processing App Update
<unknown>(0xa06991a8): ALWAYS| End processing App Update
```

If the screen doesn't turn black paste the whole console output.

PS: If you have the League of Legends application in a different folder change the first line accordingly.

**Comment by hbZwart** [comment]
Screen doesnt turn black, terminal says there is a file missing
 -bash: /Applications/League of Legends.app/Contents/LOL/RADS/solutions/lol_game_client_sln/releases/*/deploy/LeagueOfLegends.app/Contents/MacOS/LeagueofLegends: No such file or directory

**Comment by tiagoblackcode** [comment]
Hmm, that's strange. It means your bash isn't expanding the `*` (wildcard) like it should. 

To hotfix this, in the line that begins with `gameclientpath=$( ... )` replace the `*` with `0.0.0.133` (that's the version of LoL I'm running at the moment). In the line that begins with `airclientbinary` replace the `*` with `0.0.0.144`:

```
lolpath=/Applications/League\ of\ Legends.app
gameclientpath=$( echo $lolpath/Contents/LOL/RADS/solutions/lol_game_client_sln/releases/0.0.0.133/deploy/LeagueOfLegends.app )
airclientbinary=$( echo $lolpath/Contents/LOL/RADS/projects/lol_air_client/releases/0.0.0.144/deploy/bin/LolClient )

cd "$gameclientpath/Contents/MacOS"

riot_launched=true \
"$gameclientpath/Contents/MacOS/LeagueofLegends" \
"8394" "LoLPatcher" \
"$airclientbinary" \
"spectator 110.45.191.11:80 abcdefg 0000 KR"
```

That should do the trick.

**Comment by hbZwart** [comment]
Screen turned black, console now says
<unknown>(0xa12c31a8): ALWAYS| Sleeping
<unknown>(0xa12c31a8): ALWAYS| Start processing App Update
<unknown>(0xa12c31a8): ALWAYS| End processing App Update
<unknown>(0xa12c31a8): ALWAYS| Sleeping
<unknown>(0xa12c31a8): ALWAYS| Start processing App Update
<unknown>(0xa12c31a8): ALWAYS| End processing App Update
<unknown>(0xa12c31a8):  ERROR| Timeout while waiting for replay system to get game metadata from the cloud
<unknown>(0xb031d000): ALWAYS| Spectator server version retrieved: 
<unknown>(0xb031d000):  ERROR| ReplayNetClient GetGameMetaData error. HTTP status code: 500
<unknown>(0xb031d000):  ERROR| Replay metadata retrieve Failure!!
<unknown>(0xb031d000): ALWAYS| ---- Waiting to fetch 31199
<unknown>(0xb031d000): ALWAYS| Spectator server version retrieved: 
<unknown>(0xb031d000):  ERROR| ReplayNetClient GetGameMetaData error. HTTP status code: 500
<unknown>(0xb031d000):  ERROR| Replay metadata retrieve Failure!!
<unknown>(0xb031d000): ALWAYS| ---- Waiting to fetch 32351
<unknown>(0xb031d000): ALWAYS| Spectator server version retrieved: 
<unknown>(0xb031d000):  ERROR| ReplayNetClient GetGameMetaData error. HTTP status code: 500
<unknown>(0xb031d000):  ERROR| Replay metadata retrieve Failure!!
<unknown>(0xb031d000): ALWAYS| ---- Waiting to fetch 35597

(There were a lot more loops of the: Sleeping -> Start processing -> end processing -> sleeping however didnt want to paste all of them as there are many)

What should i do now?

**Comment by tiagoblackcode** [comment]
That means the game is starting properly. Now let's test if you can spectate an arbitrary game. Go to http://www.op.gg/spectate/pro and download a spectate file. After you download it open it in a text editor (TextEdit.app) and go to the line 139 that begins with `@start "" "League of Legends.exe" ...` and copy the part that says `"spectator ... KR/EUW1/..."`, replace the last line of the script above with what you copied and run it in them Terminal.app again.

If this works and you are able to spectate the game, then the problem is with the spectate application. This being the case, I believe the system call the application does it's not the same the game does when running a spectate session. We then have to wait for feedback from the developers so they can change the code accordingly.

**Comment by genesor** [comment]
I'll update the way the app launches the spectate mode and remove the "*" in the path.
To do so I'll need to detect the current version of lol_game_client_sln and lol_air_client.

**Comment by tiagoblackcode** [comment]
@Genesor It can be. I'm using `zsh` and the shell expands the `*` but @Coprosmo wasn't able to do the same.

Also, there's a slight difference between your call and LoLClient's call. You use `LoLLauncher` as 3rd argument where as LoLClient uses `LoLLauncher`. Nevertheless, I can get the spectator up and running using both although I think you should try to get your system call as close as possible to the one used by LoLLauncher.

**Comment by hbZwart** [comment]
It worked c:

**Comment by terbmada** [comment]
What do I do if my game doesn't start properly? My LoL application still crashes on launch.
I entered in the paths and even changed it to 0.0.0.134 because it is updated now and it still crashes.

**Comment by tiagoblackcode** [comment]
Can you paste the console output here? Assuming you're using the script I pasted above.

**Comment by terbmada** [comment]
Console says after pasting your script:
<unknown>(0xa0b1f1a8): ALWAYS| Global logging level set to   OKAY
<unknown>(0xa0b1f1a8): ALWAYS| Loading RADS dynamic library: /Applications/League of Legends.app/Contents/LOL/RADS/solutions/lol_game_client_sln/releases/0.0.0.134/deploy/LeagueOfLegends.app/Contents/MacOS/libRiotRadsIO.dylib
<unknown>(0xa0b1f1a8):   WARN| RADS::API::Impl::RuntimeEnvironment::RuntimeEnvironment(HRESULT &, Common::ReleaseManifestCache &, bool, const std::string &): Did not find keywords "projects" or "solutions" in path
<unknown>(0xa0b1f1a8):   WARN| RADS::API::Impl::Main::Main(HRESULT &, const std::string &): Could not determine solution or project runtime environment, execution will continue but all files will be treated as unmanaged in the current folder.
<unknown>(0xa0b1f1a8): ALWAYS| Loaded RADS dynamic library: /Applications/League of Legends.app/Contents/LOL/RADS/solutions/lol_game_client_sln/releases/0.0.0.134/deploy/LeagueOfLegends.app/Contents/MacOS/libRiotRadsIO.dylib
<unknown>(0xa0b1f1a8): ALWAYS| Data overlay start folder initialized to DATA, Content/Src
2014-09-17 16:19:17.486 LeagueofLegends[80714:507] BugSplatFramework: initWithDatabase: defaultExceptionHandler is set
<unknown>(0xa0b1f1a8): ALWAYS| Global logging level set to   WARN
<unknown>(0xa0b1f1a8): ALWAYS| Build Version: Mac Beta Version 4.16.0.253 (Sep 12 2014/15:28:26) [PUBLIC] <Releases/4.16> ChangeList: 713061
<unknown>(0xa0b1f1a8): ALWAYS| OS Version String: MacOSX Version 10.9.4
<unknown>(0xa0b1f1a8): ALWAYS| Measured processor speed: 2800
<unknown>(0xa0b1f1a8): ALWAYS| CPU: Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz (4 core)
<unknown>(0xa0b1f1a8): ALWAYS| Display info: Graphics/Displays:

```
Intel HD Graphics 3000:

  Chipset Model: Intel HD Graphics 3000
  Type: GPU
  Bus: Built-In
  VRAM (Total): 384 MB
  VRAM (Dynamic, Max): 10
  Vendor: Intel (0x8086)
  Device ID: 0x0126
  Revision ID: 0x0009
  Displays:
    Color LCD:
      Display Type: LCD
      Resolution: 1280 x 800
      Pixel Depth: 32-Bit Color (ARGB8888)
      Main Display: Yes
      Mirror: Off
      Online: Yes
      Built-In: Yes
```

<unknown>(0xa0b1f1a8): ALWAYS| Physical memory: 4294967296
<unknown>(0xa0b1f1a8): ALWAYS| Started System Init
<unknown>(0xb031d000): ALWAYS| Started ReplayDownloadManager thread.
<unknown>(0xa0b1f1a8): ALWAYS| Maestro Init
<unknown>(0xb031d000): ALWAYS| ==== Fetch MetaData Phase ====
<unknown>(0xb031d000): ALWAYS| ---- Waiting to fetch 5000
<unknown>(0xa0b1f1a8): ALWAYS| Maestro completed init
<unknown>(0xa0b1f1a8): ALWAYS| zip manifest, 'ClientZips.txt', not found (expected).
<unknown>(0xa0b1f1a8): ALWAYS| Replay mode
<unknown>(0xa0b1f1a8): ALWAYS| StartSession called
<unknown>(0xa0b1f1a8): ALWAYS| Started Init event arguments
<unknown>(0xa0b1f1a8): ALWAYS| Waiting until connection...
<unknown>(0xa0b1f1a8): ALWAYS| InitRenderer() enter
<unknown>(0xa0b1f1a8): ALWAYS| r3dRenderLayer::Init(0x03f85590) enter
<unknown>(0xa0b1f1a8): ALWAYS| r3dRenderLayer::Init() exit successfully
<unknown>(0xa0b1f1a8):  ERROR| Failed to load any localizations!
<unknown>(0xa0b1f1a8): ALWAYS| SharedConfigPath: /Applications/League of Legends.app/Contents/LOL/RADS/projects/lol_air_client/releases/0.0.0.145/deploy/preferences/
<unknown>(0xa0b1f1a8): ALWAYS| r3dRenderLayer::SetMode(XRes = 1280, YRes = 800, BPP = 32,  Flags=4) enter
<unknown>(0xa0b1f1a8): ALWAYS| r3dRenderLayer::SetMode: Creating d3d device
<unknown>(0xa0b1f1a8):  ERROR| Can not open file <Point1_a.dds> *********
<unknown>(0xa0b1f1a8):  ERROR| Failed to load Point1_a.dds
<unknown>(0xa0b1f1a8):   WARN| r3dTexture EX: Point1_a.dds - not found. Dummy texture created.
<unknown>(0xa0b1f1a8):  ERROR| Can not open file <Spot_a.dds> *********
<unknown>(0xa0b1f1a8):  ERROR| Failed to load Spot_a.dds
<unknown>(0xa0b1f1a8):   WARN| r3dTexture EX: Spot_a.dds - not found. Dummy texture created.
<unknown>(0xa0b1f1a8):  ERROR| Can not open file <White.dds> *********
<unknown>(0xa0b1f1a8):  ERROR| Failed to load White.dds
<unknown>(0xa0b1f1a8):   WARN| r3dTexture EX: White.dds - not found. Dummy texture created.
<unknown>(0xa0b1f1a8):  ERROR| Can not open file <Blank.dds> *********
<unknown>(0xa0b1f1a8):  ERROR| Failed to load Blank.dds
<unknown>(0xa0b1f1a8):   WARN| r3dTexture EX: Blank.dds - not found. Dummy texture created.
<unknown>(0xa0b1f1a8):  ERROR| Can not open file <Missing.dds> *********
<unknown>(0xa0b1f1a8):  ERROR| Failed to load Missing.dds
<unknown>(0xa0b1f1a8):   WARN| r3dTexture EX: Missing.dds - not found. Dummy texture created.
<unknown>(0xa0b1f1a8):  ERROR| Can not open file <Toon.dds> *********
<unknown>(0xa0b1f1a8):  ERROR| Failed to load Toon.dds
<unknown>(0xa0b1f1a8):   WARN| r3dTexture EX: Toon.dds - not found. Dummy texture created.
<unknown>(0xa0b1f1a8): ALWAYS| r3dRenderLayer::SetMode: Initialize shaders for current rendering path
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\Dilate\PS_2PASS_DILATE_FILTER_1.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\Dilate\PS_2PASS_DILATE_FILTER_2.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\Dilate\PS_2PASS_DILATE_FILTER_3.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\Dilate\PS_2PASS_DILATE_FILTER_4.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\Dilate\PS_2PASS_DILATE_FILTER_5.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\Dilate\PS_2PASS_DILATE_FILTER_6.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\Dilate\PS_2PASS_DILATE_FILTER_7.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\Dilate\PS_2PASS_DILATE_FILTER_8.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\Dilate\PS_2PASS_DILATE_FILTER_9.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\PS_DILATE_FILTER.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\PS_DILATE_FILTER3.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\PS_COPY_FILTER.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\PS_COPY_FILTER_WITH_COLOR_MOD.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/MouseOver\PS_APPLY_MASK.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\PS_TOON_INKING_FILTER.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\Gauss.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Filters\BlitScreenTransition.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/FXAA_PS.ps_3_0> 
<unknown>(0xa0b1f1a8):  ERROR| VertexShader::Compile: failed to open file <Data/Shaders/HLSL/Renderer/VS_SCREENVERTEX.vs_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| VertexShader::Compile: failed to open file <Data/Shaders/HLSL/Renderer/VS_SCREENVERTEX_SCALE_AND_BIAS.vs_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| VertexShader::Compile: failed to open file <Data/Shaders/HLSL/Renderer/VS_SCREENVERTEX_SCALE_AND_BIAS_AND_ROTATE.vs_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| VertexShader::Compile: failed to open file <Data/Shaders/HLSL/Renderer/VS_SIMPLEWORLDVERTEX.vs_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| VertexShader::Compile: failed to open file <Data/Shaders/HLSL/Renderer/VS_WORLDVERTEX.vs_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Renderer/PS_SCREENVERTEX.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Renderer/PS_SIMPLEWORLDVERTEX.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Renderer/PS_WORLDVERTEX.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/Renderer/PS_SCREENVERTEX.ps_2_0> 
<unknown>(0xa0b1f1a8): ALWAYS| r3dRenderLayer::RecreateOwnedResources
<unknown>(0xa0b1f1a8): ALWAYS| r3dRenderLayer::SetMode exit successfully
<unknown>(0xa0b1f1a8):  ERROR| Can not open file <wall_of_grass_mask.dds> *********
<unknown>(0xa0b1f1a8):  ERROR| Failed to load wall_of_grass_mask.dds
<unknown>(0xa0b1f1a8):   WARN| r3dTexture EX: wall_of_grass_mask.dds - not found. Dummy texture created.
<unknown>(0xa0b1f1a8): ALWAYS| In Riot::Win::Resize: Resizing the window and retrieving monitor info
<unknown>(0xa0b1f1a8): ALWAYS| In Riot::Win::Resize: Initial VideoMode(3c97210) and resolution (1280 x 800) 
<unknown>(0xa0b1f1a8): ALWAYS| In Riot::Win::Resize: VideoMode(3c97210) and resolution (640 x 400) 
<unknown>(0xa0b1f1a8): ALWAYS| In Riot::Win::Resize: Resized window to resolution 1280x800
<unknown>(0xa0b1f1a8):  ERROR| Failed to load font size and resolution file. Game fonts will not work!
<unknown>(0xa0b1f1a8):  ERROR| Assertion failed!

File: /jenkins/workspace/game-code-Releases-4-16-public-mac/code/Game/LoL/UX/Font/Client/GameFontManager.cpp
Line: 99

Function: Riot::RenderGlyph::FontDescription <anonymous namespace>::CreateEternityDescFromFontDesc(const GameFontSystem::GameFontData &, float &)

Expression: !fontTypes.empty()
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/RenderGlyph/PS_RENDER_FILL_AND_OUTLINE.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| PixelShader::Load: failed to open file <Data/Shaders/HLSL/RenderGlyph/PS_RENDER_GLOW.ps_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| VertexShader::Compile: failed to open file <Data/Shaders/HLSL/RenderGlyph/VS_RENDER_FILL_AND_OUTLINE.vs_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| VertexShader::Compile: failed to open file <Data/Shaders/HLSL/RenderGlyph/VS_RENDER_GLOW.vs_2_0> 
<unknown>(0xa0b1f1a8):  ERROR| virtual HRESULT RADS::API::Impl::Main::OpenFile(const std::string &, const RADS::API::FILE_TYPE, boost::shared_ptr<IFile> &) const: Empty file name
<unknown>(0xa0b1f1a8):  ERROR| FontMappings.txt was missing or otherwise unable to open
2014-09-17 16:19:21.596 LeagueofLegends[80714:507] BugSplatFramework: exceptionHandler: shouldLogException name: NSUncaughtSystemExceptionException
reason: Uncaught system exception: signal 10
mask: 4
2014-09-17 16:19:21.596 LeagueofLegends[80714:507] NSExceptionHandler has recorded the following exception:
NSUncaughtSystemExceptionException -- Uncaught system exception: signal 10
Stack trace:  0x9b29389d  0x9435fdeb  0xffffffff  0x6463e9  0x63f586  0x64511f  0x3b35c3  0x3b1ba2  0x3ae971  0x1bf8a8  0x1ec07c
2014-09-17 16:19:21.597 LeagueofLegends[80714:507] BugSplatFramework: exceptionHandler: shouldHandleException name: NSUncaughtSystemExceptionException
reason: Uncaught system exception: signal 10
mask: 8
2014-09-17 16:19:21.597 LeagueofLegends[80714:507] BugSplatFramework: getCrashReport: /Users/Adam/Library/Logs/DiagnosticReports/LeagueofLegends
2014-09-17 16:19:21.651 LeagueofLegends[80714:507] BugSplatFramework: sendCrashReport: BugsplatReporter is running
2014-09-17 16:19:21.762 BugsplatReporter[80731:303] BugsplatReporter: initialize
2014-09-17 16:19:21.763 BugsplatReporter[80731:303] BugsplatReporter: init
2014-09-17 16:19:21.763 BugsplatReporter[80731:303] BugsplatReporter: fetchParams
2014-09-17 16:19:21.764 BugsplatReporter[80731:303] BugsplatReporter: initialized
2014-09-17 16:19:21.764 BugsplatReporter[80731:303] BugsplatReporter: awakeFromNib
objc[80731]: Class SIMBL is implemented in both /Users/Adam/Library/ScriptingAdditions/EasySIMBL.osax/Contents/MacOS/EasySIMBL and /Library/ScriptingAdditions/SIMBL.osax/Contents/MacOS/SIMBL. One of the two will be used. Which one is undefined.
 -- 
Warning: /usr/bin/atos is moving and will be removed from a future OS X release.
It is now available in the Xcode developer tools to be invoked via: `xcrun atos`
To silence this warning, pass the '-d' command-line flag to this tool.
 -- 
2014-09-17 16:19:21.980 LeagueofLegends[80714:507] BugSplatFramework: exceptionHandler: NSExceptionHandlerUncaughtSignalHandler (in ExceptionHandling) + 60
_sigtramp (in libsystem_platform.dylib) + 43
0xffffffff
0x006463e9 (in LeagueofLegends) + 217
0x0063f586 (in LeagueofLegends) + 486
0x0064511f (in LeagueofLegends) + 287
0x003b35c3 (in LeagueofLegends) + 1043
0x003b1ba2 (in LeagueofLegends) + 2658
0x003ae971 (in LeagueofLegends) + 289
0x001bf8a8 (in LeagueofLegends) + 2664
0x001ec07c (in LeagueofLegends) + 1596
Bus error: 10

**Comment by tiagoblackcode** [comment]
Can you tell me whats the path when you try to run the spectator session? Paste the output of `pwd` here.

From the looks of the console output it seems like your LoL installation is corrupted in some way because Riot's RADS system, which is responsible for creating a "virtual filesystem" for the game to load files, isn't finding the `projects` and `solutions` folder. Because of that, subsequent file load calls throw an error which halts the game bootstrapping process.

Another thing I noticed is that the RADS library is loaded from a different path than mine

```
 /Applications/League of Legends.app/Content/LOL/RADS/libRiotRadsIO.dylib
```

where as yours is

```
 /Applications/League of Legends.app/Contents/LOL/RADS/solutions/lol_game_client_sln/releases/0.0.0.134/deploy/LeagueOfLegends.app/Contents/MacOS/libRiotRadsIO.dylib
```

**Comment by terbmada** [comment]
How do I give you the output of pwd? Sorry I'm not that much of a technical person...

**Comment by tiagoblackcode** [comment]
After running the script (and the game crashing) in the same console window you ran the script write `pwd` and press `Enter`.

**Comment by terbmada** [comment]
Ah, thanks, the path is /Applications/League of Legends.app/Contents/LOL/RADS/solutions/lol_game_client_sln/releases/0.0.0.134/deploy/LeagueOfLegends.app/Contents/MacOS

**Comment by tiagoblackcode** [comment]
I have yet to find out why your game doesn't start. The game is not finding the assets (game models etc) maybe due to your rads library being in a different place.

Do this, start a game and then go to the terminal app and paste the following:

```
  ps -ef -wwE | grep LolClient | sed -E 's/(USER|LOGNAME|HOME)=[^ ]*//g'
```

Then paste the output here (the last part is to ensure your privacy by hiding some env variables). This will show how the game is called by the Launcher whenever you play a game and can be useful to determine if there are any arguments to tell RADS library where to find the assets.

Another thing you can try is copying the RADS library to where it usually is - `/Applications/League of Legends.app/Contents/LOL/RADS/libRiotRadsIO.dylib`.

First, check if I'm right by doing this on the terminal:

```
find /Applications/League\ of\ Legends.app -type f -name 'libRiotRadsIO.dylib'
```

Check if there is no entry like the one I showed above and also if this yields any results. If there are no entries on `/Applications/League of Legends.app/Contents/LOL/RADS/libRiotRadsIO.dylib` but others, do this:

```
cp "$( find /Applications/League\ of\ Legends.app -type f -name 'libRiotRadsIO.dylib' | head -n 1 )" "/Applications/League of Legends.app/Contents/LOL/RADS/
```

This will copy the first RADS library it finds to the appropriate place. After this try and spectate a game using the script I wrote in previous posts and paste the output here in case the game does not start.

**Comment by terbmada** [comment]
I started a game and pasted the script you said and got:
ps -ef -wwE | grep LolClient | sed -E 's/(USER|LOGNAME|HOME)=[^ ]*//g'
  501 11495 11383   0  5:20am ??         0:58.40 /Applications/League of Legends.app/Contents/LOL/RADS/projects/lol_air_client/releases/0.0.0.148/deploy/bin/LolClient -runtime .\ -nodebug META-INF\AIR\application.xml .\ -- 8393 SHELL=/bin/bash __CHECKFIX1436934=1 DISPLAY=/tmp/launch-axIpyi/org.macosforge.xquartz:0  riot_launched=true SSH_AUTH_SOCK=/tmp/launch-34YfDF/Listeners  __CF_USER_TEXT_ENCODING=0x1F5:0:0 Apple_PubSub_Socket_Render=/tmp/launch-ZsDnOd/Render TMPDIR=/var/folders/7r/w0_f6d_55vz09djr7vtcjpbw0000gn/T/ PATH=/usr/bin:/bin:/usr/sbin:/sbin 
  501 13509 11383   0  5:31am ??         0:06.44 /Applications/League of Legends.app/Contents/LOL/RADS/solutions/lol_game_client_sln/releases/0.0.0.137/deploy/LeagueOfLegends.app/Contents/MacOS/LeagueofLegends 8394 LoLPatcher /Applications/League of Legends.app/Contents/LOL/RADS/projects/lol_air_client/releases/0.0.0.148/deploy/bin/LolClient 103.240.226.47 5132 4MQCCrzl0Df5/dtiFWs8MQ== 282571 SHELL=/bin/bash __CHECKFIX1436934=1 DISPLAY=/tmp/launch-axIpyi/org.macosforge.xquartz:0  riot_launched=true SSH_AUTH_SOCK=/tmp/launch-34YfDF/Listeners  __CF_USER_TEXT_ENCODING=0x1F5:0:0 Apple_PubSub_Socket_Render=/tmp/launch-ZsDnOd/Render TMPDIR=/var/folders/7r/w0_f6d_55vz09djr7vtcjpbw0000gn/T/ PATH=/usr/bin:/bin:/usr/sbin:/sbin 
  501 13570 13560   0  5:31am ttys000    0:00.00 grep LolClient TERM_PROGRAM=Apple_Terminal SHELL=/bin/bash TERM=xterm-256color TMPDIR=/var/folders/7r/w0_f6d_55vz09djr7vtcjpbw0000gn/T/ Apple_PubSub_Socket_Render=/tmp/launch-ZsDnOd/Render TERM_PROGRAM_VERSION=326 TERM_SESSION_ID=0BFD70BE-658A-430A-9B77-B96E9F69926D  SSH_AUTH_SOCK=/tmp/launch-34YfDF/Listeners __CF_USER_TEXT_ENCODING=0x1F5:0:0 PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin __CHECKFIX1436934=1 PWD=/Users/Adam LANG=en_AU.UTF-8 SHLVL=1   DISPLAY=/tmp/launch-axIpyi/org.macosforge.xquartz:0 _=/usr/bin/grep

Also I looked using the find script you pasted and there already was a RADS library in /Applications/League of Legends.app/Contents/LOL/RADS/libRiotRadsIO.dylib ! Would maybe copying or deleting the RADS library that is in the incorrect place work?
