### ISSUE TITLE
Black screen, replay never loads

### ISSUE THREAD

**Issue by custerc** [genesor/OPGG_Spectate_Mac#14]
This was working great for the first week or so I downloaded it, but since then when I try to load a replay file it just puls up a black screen. I can still see the mouse, but nothing else ever happens, and I end up having to hard reset my computer to get out of it.

**Comment by ghost** [comment]
Same problem here. Help pls

**Comment by xMachete96** [comment]
I have the same problem, i don't know how to fix it. help pls
