### ISSUE TITLE
Can't get file in 

### ISSUE THREAD

**Issue by peteyyy** [genesor/OPGG_Spectate_Mac#20]
When I try to drag the .sh file on to it, it says "drop file here" when its hovered over, but when i drop it nothing happens. I also tried to open with, and that didn't work either (not that it necessarily needs to, but still).

**Comment by god-devil** [comment]
me 2, pls help!!!

**Comment by pkkss** [comment]
me 2 and other 30 friends
pls help

**Comment by fedmyster** [comment]
same:/

**Comment by Nosreme** [comment]
I am also having the same problem.

**Comment by Dragonwin4** [comment]
I had this just now and i found a way. If you are on a mac then right click it and to go "get info". Then, you want to change the file extension so it just displays something along the lines of (just an example) LOL_OPGG_Observer_1884332564_spectate(1).cmd

If you have a (1) or any other number like that, delete it. If you don't, then you are set to go. Simply place the file into the spectator and it should work. Hope I helped ^_^.

**Comment by Quicken2k2** [comment]
Im having the same issue right now but i can't tell if it's op.gg or the op.gg spectate program. I tried the above but my file doesn't have a (1). It still won't load
