### ISSUE TITLE
New file type not working

### ISSUE THREAD

**Issue by Dutched** [genesor/OPGG_Spectate_Mac#22]
OPGG had a big server update yesterday and I'm not sure if it affected this but now when I download the replay file it's as a .cmd file. I haven't tried out the program until yesterday but it doesn't seem like it's the right file type. Any idea how to change the file type?

**Comment by Jhilla2** [comment]
Just open "get info" and replace the .cmd extension to .sh and the file should work again.

**Comment by Dutched** [comment]
That worked! Thanks so much
