### ISSUE TITLE
Unable to download spectator data

### ISSUE THREAD

**Issue by Cyonara** [genesor/OPGG_Spectate_Mac#23]
Even after renaming the file to .sh, I always get "Unable to download spectator data. The game will now exit".
Everyone in the loading screen is 100%...
Any solutions...? >,<

**Comment by winkyfrown** [comment]
Having the same issue here. If it matters. I'm in NA and have tried spectating games from the NA server (http://na.op.gg/match/observer/id=1737911529) and KR server. (http://www.op.gg/match/observer/id=1754868013) (http://www.op.gg/match/observer/id=1754784638)
