### ISSUE TITLE
All summoners are "not connected".

### ISSUE THREAD

**Issue by Blaman123** [genesor/OPGG_Spectate_Mac#25]
Hi there.

First, thanks for creating this in the first place. I only have a mac and would love to finally see some replays.

I downloaded the OP.GG Spectate 1.0.1. I then downloaded the replay from op.gg. I renamed the end from .cmd to .sh. I drag it into the app. It opens the LoL client and starts loading the game. But then the summoners never show up and it only says "not connected". I can see the summoner names, but no pictures of the champs and the game doesn't start.

Is that because of the new patch? I tried 2 recordings from yesterday. If you have any idea how to fix it, I would be happy. Couldn't find anything on the net regarding this issue yet.

Thanks!

**Comment by genesor** [comment]
It's due to the op.gg replay feature wich is still in beta.
