### ISSUE TITLE
Unable to Download Spectator Data

### ISSUE THREAD

**Issue by Curbob11** [genesor/OPGG_Spectate_Mac#27]
When I try to load one of my files downloaded from OP.GG, it will show the champion loading screen and after a couple minutes it will say, "Unable to download spectator data, the game will now exit", how do I fix this?

(Mac OS X Version 10.9.5)

**Comment by Arkades** [comment]
Same thing for me. After the file get dropped in, the loading game starts, few minutes later it stays stuck at 100% for all the champs and says : "Unable to download spectator data, the game will now exit".

I just downloaded the OP.GG Spectate 1.0.1 few minutes earlier and this was my first tries.

(Mac OS X Yosemite 10.10.1)

**Comment by genesor** [comment]
Like every other people you try to use op.gg or another beta feature replay. It's not due to the client.
