### ISSUE TITLE
op.gg spectator

### ISSUE THREAD

**Issue by desertfoxx** [genesor/OPGG_Spectate_Mac#29]
It downloaded the replay .cmd file i drag it to the app and nothing happens. I have league open. ?? I just downloaded it, maybe they changed something this patch?

**Comment by nammyc** [comment]
I have the same problem

**Comment by genesor** [comment]
Yep they changed something in the new patch I've to investigate the problem.

**Comment by desertfoxx** [comment]
Is there a way to launch it from terminal?

**Comment by Mawgli** [comment]
.bat files doesn't work either

**Comment by Nosreme** [comment]
I am also having issues.  Earlier today I tried to open some replay files with .cmd extensions and .sh extensions (which I'd had success on previously).  The client would open and get to the loading screen, but the only thing showing was the players names and the typical blank "not connected" champion splash art box.  Then the app would force quit and the client would give me an error message.  However, I am now no longer able to recreate those results.  Now the LoL client doesn't open at all.

**Comment by sp91ew** [comment]
exactly the same issue 9 July 2015. I drop the cmd file on the gui while having the LoL client open and logged in and nothing happens.

Any update :/ ?
