### ISSUE TITLE
The game is unable to download spectator data

### ISSUE THREAD

**Issue by julian-poidevin** [genesor/OPGG_Spectate_Mac#3]
Hi,

I've downloaded 2 replays from op.gg (EUW), dropped them into the app. I can access to the loading screen but when everyone is at 100% I got this message : http://imgur.com/TAawhJy

Here's the two replay files : 
- http://pastebin.com/ZPPCUJDZ
- http://pastebin.com/pKsqp2BY

Thanks a lot for your work :)

**Comment by julian-poidevin** [comment]
Why was the issue closed ? I tried to download the new version and it's still not working. Any ideas ?

**Comment by genesor** [comment]
Because it's not related to the app, it's related to your LoL client and/or your firewall and/or network and/or op.gg beta replay mode.
