### ISSUE TITLE
You can not record in the DB error

### ISSUE THREAD

**Issue by Eliat** [genesor/OPGG_Spectate_Mac#31]
Hi there,

I have followed the steps that I believe I need to follow, however whenever I click record I get the error which according to google translates too: You can not record in the DB. Could you advise how I get around this problem I have tried in both chrome and safari.

Thanks

![screen shot 2015-07-11 at 03 49 39](https://cloud.githubusercontent.com/assets/8928266/8632010/e465a5b4-277f-11e5-8e38-475ee4ae8c46.png)

**Comment by genesor** [comment]
How is it related to my app ?

**Comment by Eliat** [comment]
Sorry I was under the impression you were in charge of opp.gg
