### ISSUE TITLE
Mac shortcuts are not working

### ISSUE THREAD

**Issue by julian-poidevin** [genesor/OPGG_Spectate_Mac#4]
When pressing CMQ + Q or CMD + M the app doesn't close or minimize.

**Comment by genesor** [comment]
I'm aware of this issue and I'll patch it soon.
Thx for the feedback

**Comment by genesor** [comment]
It's fixed.
Current version supports CMD+Q and CMD+W to quit. I'll upload a new one tomorrow with the CMD+M to minimize
