### ISSUE TITLE
Connection to server failed

### ISSUE THREAD

**Issue by jeromepui** [genesor/OPGG_Spectate_Mac#6]
After a few seconds on black screen, there is a pop-up that says "Connection to server failed, want to retry?" I press retry but it doesn't work again. Pls help! Thanks!

**Comment by genesor** [comment]
This issue isn't related to my app, it's a problem with op.gg servers and riot servers.

**Comment by jeromepui** [comment]
So, is there anything I can do to solve this?

**Comment by genesor** [comment]
Change your replay/spectate file. I don't really know sorry
